#!/bin/bash
. ~/.config/HyprV/hyprv.conf

get_theme() {
    # Check which waybar theme is set
    THEMEIS=$(readlink -f ~/.config/waybar/style.css | cut -d '-' -f3)

    #if the theme is not dark then we need to switch to it
    if [[ $THEMEIS == "dark.css" ]]; then
        SWITCHTO="-dark"
        MODESTR="Dark"
    else
        SWITCHTO=""
        MODESTR="Light"
    fi
}

update_theme() {
  #set the xfce and GTK theme
  xfconf-query -c xsettings -p /Net/IconThemeName -s "Papirus-Dark"
  gsettings set org.gnome.desktop.interface icon-theme "Papirus-Dark"
  xfconf-query -c xsettings -p /Net/ThemeName -s "Adwaita$SWITCHTO"
  gsettings set org.gnome.desktop.interface gtk-theme "Adwaita$SWITCHTO"
}

restart_waybar() {
    #restart the waybar
    pkill waybar
    waybar
}

set_current_background() {
    get_theme
   
    if [[ ! -z "$SET_BG" ]]; then
        #set the current background
        if [[ $THEMEIS == "dark.css" ]]; then
            swww img ~/.config/HyprV/backgrounds/'v2-background-dark.jpg'
        else
            swww img ~/.config/HyprV/backgrounds/'v2-background.jpg'
        fi
    else
        swww img $SET_BG
    fi
}
